In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset.csv')
df.head()

english_statement                 intent programming_statement  \
0            i equals zero  arithmetic_expression                  i =0   
1        i not equals zero  arithmetic_expression                 i !=0   
2         i less than zero  arithmetic_expression                  i <0   
3      i greater than zero  arithmetic_expression                  i >0   
4  i less than equals zero  arithmetic_expression                 i <=0   

       audio_file_name  
0  audio-438153821.mp3  
1  audio-668324927.mp3  
2  audio-624815281.mp3  
3  audio-810256478.mp3  
4  audio-397931780.mp3

EXPLORATORY DATA ANALYSIS

In [15]:
import matplotlib.pyplot as plt
import IPython.display as ipd
import librosa
import librosa.display
%matplotlib inline

In [3]:
#Visualising the audio file
plt.figure(figsize=(14,5))
filename = 'D:\\7th Semester\\PROJECT-WORK-PHASE-1\\CODEX-PROJECT-REPO\DEMO-TEST-FILES\\test_file_wav.wav'
audio_file,sample_rate = librosa.load(filename)
librosa.display.waveshow(audio_file,sr=sample_rate)
ipd.Audio(filename)

NameError: name 'plt' is not defined

In [18]:
#constant sample rate of librosa library
sample_rate

22050

In [27]:
#Normalised Data from Librosa
audio_file[10000:]

array([-0.03002885, -0.05616896, -0.08092307, ...,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [20]:
#Using Alternative package like scipy.io.wavfile
from scipy.io import wavfile as wav
wav_sample_rate,wave_audio = wav.read(filename)

In [21]:
#Variable Sample rate
wav_sample_rate

24000

In [30]:
#Non Normalised representation of wavfile
wave_audio[10000:]

array([-6805, -6857, -6524, ...,     0,     0,     0], dtype=int16)

DATA PRE-PROCESSING

In [37]:
#Feature Extraction
filename = 'D:\\7th Semester\\PROJECT-WORK-PHASE-1\\CODEX-PROJECT-REPO\\DEMO-TEST-FILES\\test_file_wav.wav'
audio_file,sample_rate = librosa.load(filename)

In [39]:
audio_file

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [33]:
#Feature Extraction - Mel Frequency Cepstral Co efficient
mfccs = librosa.feature.mfcc(y=audio_file,sr=sample_rate,n_mfcc=40)
mfccs.shape

(40, 87)

In [40]:
mfccs

array([[-5.8517175e+02, -5.8408173e+02, -4.4085461e+02, ...,
        -5.8517175e+02, -5.8517175e+02, -5.8517175e+02],
       [ 0.0000000e+00,  1.5379781e+00,  8.1914932e+01, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.5273013e+00,  2.2608765e+01, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [ 0.0000000e+00, -1.8894018e-01, -3.9203236e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -1.9236237e-01, -2.5625687e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -1.9260266e-01,  1.3053100e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

DATA PREPROCESSING FUNCTION

In [1]:
import numpy as np
def feature_extractor(filename):
    audio_file,sample_rate = librosa.load(filename)
    features = librosa.feature.mfcc(y=audio_file,sr=sample_rate,n_mfcc=40)
    scaled_features = np.mean(features.T,axis=0)
    return scaled_features

In [4]:
print(np.array(feature_extractor(filename)))

NameError: name 'filename' is not defined

In [45]:
#List of filenames present in wav folder
from glob import glob
audio_files = glob('D:/7th Semester/PROJECT-WORK-PHASE-1/CODEX-PROJECT-REPO/FINAL_WAV_AUDIO/*.wav')
len(audio_files)

6801

In [52]:
audio_files[0]

'D:/7th Semester/PROJECT-WORK-PHASE-1/CODEX-PROJECT-REPO/FINAL_WAV_AUDIO\\audio-1001048.wav'

In [48]:
df.head()

english_statement                 intent programming_statement  \
0            i equals zero  arithmetic_expression                  i =0   
1        i not equals zero  arithmetic_expression                 i !=0   
2         i less than zero  arithmetic_expression                  i <0   
3      i greater than zero  arithmetic_expression                  i >0   
4  i less than equals zero  arithmetic_expression                 i <=0   

       audio_file_name  
0  audio-438153821.mp3  
1  audio-668324927.mp3  
2  audio-624815281.mp3  
3  audio-810256478.mp3  
4  audio-397931780.mp3

In [49]:
df.columns

Index(['english_statement', 'intent', 'programming_statement',
       'audio_file_name'],
      dtype='object')

In [63]:
df.shape

(6810, 4)

In [77]:
#Actual Data Preprocessing
from tqdm import tqdm
extracted_features = {
    "audio_representation":[],
    "program_statement":[]
}
for index,row in tqdm(df.iterrows()):
    parent_dir = 'D:/7th Semester/PROJECT-WORK-PHASE-1/CODEX-PROJECT-REPO/FINAL_WAV_AUDIO\\'
    filename = row['audio_file_name']
    filename = filename.replace('.mp3','.wav')
    filename = parent_dir+filename
    if filename in audio_files:
        extracted_features['program_statement'].append(row['programming_statement'])
        data = np.array(feature_extractor(filename))
        extracted_features['audio_representation'].append(data) 
    else:
        continue
    break

0it [00:00, ?it/s]


In [78]:
len(extracted_features)

2

In [84]:
dataset = pd.DataFrame(extracted_features)
dataset.head()
dataset.to_csv('final_dataset_1.csv')

In [81]:
dataset.dtypes

audio_representation    object
program_statement       object
dtype: object